[package]
name = "bae"
version = "0.1.1"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
edition = "2018"
description = "A Rust proc-macro attribute parser"
homepage = "https://github.com/davidpdrsn/bae"
documentation = "https://docs.rs/bae"
keywords = ["proc-macro", "attr", "attribute"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/davidpdrsn/bae.git"

[dependencies]
syn = { version = "1.0.7", features = ["full", "extra-traits"] }
quote = "1.0.2"
proc-macro2 = "1.0.6"
proc-macro-error = "0.3.4"
heck = "0.3.1"

[dev_dependencies]
trybuild = "1.0.17"

[lib]
proc-macro = true
path = "src/lib.rs"
